#!/bin/bash

case $1/$2 in
  pre/*)
    echo "$0: Going to $2..."
        ;;
  post/*)
    echo "$0: Waking up from $2..."
    gsettings set org.gnome.desktop.peripherals.keyboard delay 220
        ;;
esac


# place the script in /lib/systemd/system-sleep
# chmod a+x /lib/systemd/system-sleep/keyrepeat
