#!/bin/bash

cd
sudo apt update
curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo add-apt-repository ppa:mmstick76/alacritty
sudo apt update
sudo apt install -y synaptic gnome-tweaks gnome-shell-extensions chrome-gnome-shell nodejs vim-gtk tmux apt-transport-https curl  brave-browser alacritty trash-cli ffmpeg yarn zsh curl git tree wmctrl

vi -E -s -u ./.vimrc +PlugInstall +qall

gsettings set org.gnome.desktop.interface gtk-theme "HighContrastInverse"
gsettings set org.gnome.desktop.interface enable-animations false

wget https://github.com/w1am/dotfiles/raw/master/.vimrc .vimrc
wget https://github.com/w1am/dotfiles/raw/master/.tmux.conf .tmux.conf
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
rm -rf .zshrc
wget https://github.com/w1am/dotfiles/raw/master/.zshrc .zshrc

echo "Setup has finished 🚀"
