#!/bin/bash

sudo apt install apt-transport-https curl

sudo apt-get update
sudo apt-get install nodejs

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

cd

sudo apt-get install vim-gtk
sudo apt-get install tmux
sudo apt-get install zsh curl git

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

wget https://github.com/w1am/dotfiles/raw/master/.vimrc .vimrc
wget https://github.com/w1am/dotfiles/raw/master/.tmux.conf .tmux.conf
rm -rf .zshrc
wget https://github.com/w1am/dotfiles/raw/master/.zshrc .zshrc

sudo apt-get update
sudo apt-get install synaptic
sudo apt install gnome-tweaks
sudo apt install gnome-shell-extensions
sudo apt install chrome-gnome-shell

curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list

sudo apt update

sudo apt install brave-browser

sudo add-apt-repository ppa:mmstick76/alacritty

sudo apt install alacritty

sudo apt install trash-cli

echo "final thing to do: vi .vimrc && :PlugInstall"
